"""utils/glosario.py -- Glosario de acciones regenerativas.
Descripciones breves de las 208 acciones incluidas en la Flor de la Permacultura.
Organizado por petalo y categoria.
"""

# Descripciones breves de acciones. Cuando no hay descripcion especifica,
# se genera automaticamente a partir del nombre.
GLOSARIO = {
    # ── Petalo 0: Tierra y Naturaleza ──
    "Huertos en balcones y terrazas": "Cultivo de alimentos en espacios reducidos usando macetas, jardineras y contenedores en balcones o terrazas.",
    "Huertos en macetas recicladas": "Reutilizacion de envases, baldes y contenedores descartados como recipientes para cultivar plantas comestibles.",
    "Huertos verticales en muros o cercos": "Sistemas de cultivo que aprovechan superficies verticales (muros, cercos, rejas) para producir alimentos en poco espacio horizontal.",
    "Jardines comestibles en patios pequeños": "Diseno de jardines que combinan belleza ornamental con produccion de alimentos en patios de tamano reducido.",
    "Huertos en azoteas o techos planos": "Aprovechamiento de techos y azoteas para instalar sistemas de cultivo, mejorando aislacion termica y produccion de alimentos.",
    "Microhuertos en ventanas": "Cultivo de hierbas y verduras pequenas en el espacio de una ventana, usando contenedores compactos.",
    "Cultivo hidropónico doméstico": "Cultivo de plantas sin suelo, usando soluciones nutritivas en agua. Permite producir alimentos en interiores.",
    "Cultivo acuapónico doméstico": "Sistema que combina cria de peces con cultivo de plantas. Los desechos de los peces fertilizan las plantas.",
    "Cultivo en bolsas de cultivo o contenedores textiles": "Uso de bolsas de tela o geotextil como contenedores de cultivo, con excelente drenaje y aireacion de raices.",
    "Huertos en patios comunitarios": "Espacios de cultivo compartidos entre vecinos en areas comunes de condominios o pasajes.",
    "Huertos escolares": "Espacios de cultivo en escuelas que integran la produccion de alimentos con la educacion.",
    "Huertos en centros culturales": "Integracion de huertos productivos en espacios culturales comunitarios.",
    "Huertos en espacios públicos recuperados": "Transformacion de sitios eriazos o abandonados en huertos productivos para la comunidad.",
    "Guerrilla gardening": "Practica de sembrar plantas comestibles o nativas en espacios publicos abandonados o subutilizados, sin autorizacion formal.",
    "Cultivo de microgreens": "Germinacion y cosecha temprana de semillas comestibles (7-14 dias). Alto valor nutricional en poco espacio.",
    "Germinados en casa": "Produccion de brotes germinados de semillas (lentejas, alfalfa, etc.) en frascos o bandejas, listos en 3-5 dias.",
    "Cultivo de hongos comestibles": "Produccion de setas (ostra, shiitake) en sustrato de paja, carton o borra de cafe.",
    "Cultivo de setas en café reciclado": "Uso de borra de cafe como sustrato para cultivar hongos ostra, cerrando el ciclo de residuos organicos.",
    "Vermicompostaje doméstico": "Compostaje con lombrices rojas californianas que transforman residuos organicos en humus de lombriz.",
    "Compostaje en baldes": "Sistema simple de compostaje en baldes apilados, apto para departamentos.",
    "Compostaje bokashi": "Fermentacion anaerobica de residuos organicos con microorganismos efectivos (EM). Rapido y sin olores.",
    "Compostaje comunitario en el barrio": "Sistema de compostaje compartido entre vecinos de un barrio, reduciendo residuos a escala local.",
    "Compostaje en departamentos usando lombrices": "Vermicompostaje adaptado a espacios interiores pequenos.",
    "Creación de suelo vivo en macetas": "Preparacion de sustrato rico en microorganismos y materia organica para contenedores.",
    "Uso de microorganismos eficientes": "Aplicacion de cultivos de microorganismos beneficos (EM) para mejorar suelo, compost y salud de plantas.",
    "Uso de bioles y biofertilizantes": "Preparados liquidos fermentados a base de estiercol, hierbas y minerales para nutrir el suelo.",
    "Producción de biochar": "Carbonizacion de biomasa a baja temperatura para crear un enmienda que mejora estructura y retencion de agua del suelo.",
    "Fabricación de té de compost": "Infusion aireada de compost maduro en agua para obtener un fertilizante liquido rico en microorganismos.",
    "Plantación de árboles frutales urbanos": "Incorporacion de arboles que producen frutos comestibles en espacios urbanos.",
    "Corredores de polinizadores": "Franjas de plantas con flores que conectan areas verdes, facilitando el movimiento de abejas y otros polinizadores.",
    "Jardines para abejas nativas": "Espacios disenados con plantas que alimentan abejas nativas chilenas (no la abeja europea).",
    "Jardines de mariposas": "Plantaciones que proveen alimento y habitat para mariposas en sus diferentes etapas de vida.",
    "Jardines medicinales urbanos": "Espacios dedicados al cultivo de plantas con propiedades medicinales.",
    "Jardines aromáticos": "Cultivo de hierbas aromaticas (lavanda, romero, salvia) que ademas repelen plagas y atraen polinizadores.",
    "Refugios para insectos": "Estructuras de madera, cana y materiales naturales que ofrecen habitat a insectos beneficos.",
    "Casas para murciélagos": "Cajas refugio que atraen murcielagos, grandes controladores de mosquitos y plagas nocturnas.",
    "Bebederos para aves": "Fuentes de agua poco profundas que proveen hidratacion a aves urbanas.",
    "Restauración de pequeños espacios degradados": "Recuperacion de suelo y vegetacion en microespacios urbanos abandonados.",
    "Plantación de especies nativas en jardines": "Incorporacion de flora nativa chilena que requiere menos agua y sostiene biodiversidad local.",
    "Captación de agua lluvia en casas": "Sistemas de recoleccion de agua de lluvia desde techos residenciales para riego y otros usos.",
    "Captación de agua lluvia en edificios": "Sistemas colectivos de recoleccion en edificios multifamiliares.",
    "Barriles recolectores de agua": "Contenedores conectados a canaletas para almacenar agua de lluvia.",
    "Sistemas de infiltración en patios": "Diseños que permiten que el agua de lluvia se infiltre en el suelo en vez de escurrir al alcantarillado.",
    "Micro zanjas de infiltración": "Pequenas zanjas excavadas que capturan agua de escorrentia y la infiltran al suelo.",
    "Reutilización de aguas grises para riego": "Tratamiento y uso del agua de lavado y duchas para regar jardines y huertos.",
    "Riego por goteo casero": "Sistema de riego que entrega agua directamente a la raiz de cada planta, minimizando perdidas.",
    "Jardines de lluvia urbanos": "Depresiones plantadas que capturan agua de lluvia, la filtran y la infiltran al subsuelo.",
    "Micro humedales artificiales": "Pequenos ecosistemas acuaticos construidos que filtran agua y crean habitat para biodiversidad.",
    "Guardar semillas en casa": "Practica de recolectar y conservar semillas de cosechas propias para futuras siembras.",
    "Intercambio de semillas entre vecinos": "Compartir semillas entre vecinos para diversificar cultivos y fortalecer lazos comunitarios.",
    "Bibliotecas de semillas": "Espacios publicos donde se pueden retirar y devolver semillas, como una biblioteca de libros.",
    "Bancos comunitarios de semillas": "Reservas colectivas de semillas que preservan variedades locales y patrimonio genetico.",
    "Cultivo de variedades locales": "Preferencia por variedades tradicionales adaptadas al clima y suelo local.",
    "Multiplicación de plantas por esquejes": "Propagacion vegetativa cortando y enraizando ramas de plantas existentes.",
    "Propagación de plantas nativas": "Reproduccion de especies nativas para restauracion ecologica y jardineria.",
    "Duchas cortas": "Reduccion del tiempo de ducha para disminuir consumo de agua y energia.",
    "Cerrar la llave al lavar platos": "Habito de cerrar el grifo mientras se enjabonan los platos.",
    "Reparar fugas de agua": "Deteccion y reparacion de goteras y fugas que desperdician agua.",
    "Reutilizar agua para riego": "Usar agua de lavado de verduras, coccion u otros usos domesticos para regar plantas.",
    # ── Petalo 1: Entorno Construido ──
    "Bioconstrucción en ampliaciones": "Uso de tecnicas de construccion natural (adobe, quincha, fardos) en ampliaciones de vivienda.",
    "Uso de materiales naturales en remodelaciones": "Incorporacion de materiales como madera, piedra, tierra en renovaciones.",
    "Muros interiores de tierra o barro": "Paredes hechas con tecnicas de tierra cruda que regulan humedad y temperatura.",
    "Pinturas naturales": "Recubrimientos a base de arcilla, cal, caseina u otros ingredientes no toxicos.",
    "Aislación con materiales naturales": "Uso de paja, lana, corcho, celulosa reciclada como aislante termico.",
    "Diseño solar pasivo": "Orientacion y diseno de ventanas para captar calor solar en invierno y bloquearlo en verano.",
    "Ventilación cruzada en viviendas": "Diseno de aberturas opuestas que permiten flujo natural de aire sin ventiladores.",
    "Uso de masas térmicas": "Materiales densos (piedra, adobe, agua) que absorben calor de dia y lo liberan de noche.",
    "Sombreamiento natural con plantas": "Uso de arboles caducos, trepadoras o pergolas verdes para dar sombra estacional.",
    "Pérgolas verdes": "Estructuras cubiertas por plantas trepadoras que dan sombra y producen alimentos.",
    "Enredaderas en fachadas": "Plantas trepadoras en muros exteriores que aislan, embellecen y capturan contaminantes.",
    "Techos verdes": "Cubiertas vegetales sobre techos que aislan, absorben lluvia y crean habitat.",
    "Muros verdes": "Jardines verticales en muros que purifican aire, aislan y embellecen.",
    "Jardines verticales comestibles": "Muros verdes disenados para producir hierbas, verduras y frutos.",
    "Patios interiores con vegetación": "Incorporacion de plantas y arboles en patios centrales para microclima y bienestar.",
    "Balcones verdes": "Transformacion de balcones en jardines productivos con macetas y jardineras.",
    "Cocinas comunitarias": "Espacios compartidos para cocinar colectivamente, reduciendo energia y creando comunidad.",
    "Talleres compartidos": "Espacios equipados con herramientas que se comparten entre vecinos.",
    "Huertos en condominios": "Espacios de cultivo en areas comunes de conjuntos habitacionales.",
    "Bodegas para alimentos comunitarios": "Espacios para almacenar colectivamente cosechas y alimentos conservados.",
    "Espacios de compostaje en edificios": "Areas designadas en edificios para compostar residuos organicos de todos los residentes.",
    "Uso de pallets para jardinería": "Reutilizacion de pallets de madera como jardineras, composteras o camas elevadas.",
    "Construcción con materiales reciclados": "Uso de materiales recuperados (botellas, neumaticos, latas) en construccion.",
    "Uso de ventanas recicladas para invernaderos": "Construccion de invernaderos con ventanas descartadas.",
    "Construcción de mini invernaderos": "Estructuras pequenas para proteger plantas del frio y extender temporadas de cultivo.",
    "Reutilización de contenedores": "Adaptacion de contenedores metalicos descartados como bodegas o espacios habitables.",
    # ── Petalo 2: Herramientas y Tecnologia ──
    "Paneles solares domésticos": "Instalacion de paneles fotovoltaicos para generar electricidad a partir del sol.",
    "Calentadores solares de agua": "Sistemas que usan energia solar para calentar agua sanitaria.",
    "Cocinas solares": "Dispositivos que concentran luz solar para cocinar sin combustibles.",
    "Secadores solares de alimentos": "Estructuras que usan calor solar para deshidratar frutas, verduras y hierbas.",
    "Sistemas solares portátiles": "Paneles pequenos y baterias para cargar dispositivos o iluminar sin conexion a la red.",
    "Estufas rocket": "Estufas de lena de alta eficiencia que queman con muy poca lena y casi sin humo.",
    "Hornos de barro urbanos": "Hornos construidos con barro y paja para coccion de pan y alimentos con lena.",
    "Biodigestores domésticos pequeños": "Sistemas que transforman residuos organicos en biogas para cocinar y biofertilizante.",
    "Sistemas de riego automatizado de bajo consumo": "Riego programado con goteo o microaspersion que minimiza uso de agua.",
    "Sensores de humedad del suelo": "Dispositivos que miden la humedad de la tierra para regar solo cuando es necesario.",
    "Filtros de agua domésticos": "Sistemas caseros para purificar agua de consumo (ceramica, carbon activado, arena).",
    "Biofiltros de aguas grises": "Sistemas naturales con plantas y grava que tratan agua de lavado para reutilizarla.",
    "Sistemas de captación de condensación": "Estructuras que colectan agua del rocio y la niebla.",
    "Sistemas de almacenamiento de agua": "Estanques y cisternas para guardar agua de lluvia o de la red.",
    "Uso de bicicleta": "Transporte no motorizado que reduce huella de carbono y mejora salud.",
    "Bicicletas de carga": "Bicicletas adaptadas para transportar cosechas, herramientas o compras.",
    "Carros para transportar cosechas": "Carritos manuales para mover tierra, compost y cosechas dentro del espacio.",
    "Talleres comunitarios de reparación de bicicletas": "Espacios donde vecinos aprenden a reparar y mantener sus bicicletas.",
    "Fermentación de alimentos": "Conservacion y transformacion de alimentos mediante fermentacion (chucrut, kimchi, kombucha, kefir).",
    "Deshidratación solar": "Secado de alimentos usando energia solar para conservarlos durante meses.",
    "Conservas caseras": "Preparacion de mermeladas, encurtidos y conservas para preservar cosechas.",
    "Almacenamiento natural de alimentos": "Tecnicas tradicionales para guardar alimentos sin refrigeracion (arena, ceniza, raiz).",
    "Refrigeración pasiva": "Sistemas que enfrían sin electricidad usando evaporacion, sombra o masa termica.",
    "Apagar luces cuando no se usan": "Habito basico de ahorro energetico.",
    "Usar ampolletas LED": "Reemplazo de iluminacion incandescente o fluorescente por LED de bajo consumo.",
    "Usar electrodomésticos de bajo consumo": "Preferencia por equipos con clasificacion energetica eficiente.",
    "Desconectar cargadores": "Evitar el consumo fantasma de cargadores conectados sin uso.",
    "Usar regletas con interruptor": "Regletas que permiten cortar energia a multiples equipos con un solo interruptor.",
    # ── Petalo 3: Educacion y Cultura ──
    "Talleres de agroecología urbana": "Capacitaciones practicas sobre cultivo ecologico en la ciudad.",
    "Talleres de compostaje": "Ensenanza practica de diferentes tecnicas de compostaje domestico y comunitario.",
    "Talleres de huertos urbanos": "Formacion para crear y mantener huertos productivos en espacios urbanos.",
    "Cursos de diseño regenerativo": "Formacion en diseno de sistemas regenerativos integrando ecologia, economia y comunidad.",
    "Intercambio de saberes tradicionales": "Espacios donde personas mayores comparten conocimientos ancestrales de agricultura y plantas.",
    "Aprendizaje basado en huertos": "Metodologia educativa que usa el huerto como aula viva para multiples materias.",
    "Programas educativos en jardines escolares": "Integracion curricular de jardines y huertos en escuelas.",
    "Programas de voluntariado ambiental": "Actividades organizadas donde personas donan su tiempo para proyectos ecologicos.",
    "Programas de mentoría en agroecología": "Acompanamiento de personas experimentadas a quienes inician en agroecologia.",
    "Festivales de semillas": "Eventos comunitarios de intercambio de semillas, saberes y cultura agroecologica.",
    "Ferias de agricultura urbana": "Eventos publicos que muestran y promueven la agricultura en la ciudad.",
    "Intercambio de plantas": "Encuentros para compartir esquejes, plantines y semillas entre vecinos.",
    "Cine ambiental comunitario": "Proyecciones de documentales ambientales seguidas de conversacion comunitaria.",
    "Bibliotecas ecológicas": "Colecciones de libros y recursos sobre ecologia, permacultura y regeneracion.",
    "Murales ecológicos": "Arte mural con tematica ambiental que sensibiliza y embellece el barrio.",
    "Música comunitaria": "Actividades musicales colectivas que fortalecen vinculos y cultura local.",
    "Arte con materiales reciclados": "Creacion artistica reutilizando materiales descartados.",
    "Teatro ambiental": "Obras teatrales que abordan temas ecologicos y de regeneracion.",
    "Redes de huertos urbanos": "Conexion entre diferentes huertos de una ciudad para compartir experiencias y recursos.",
    "Redes de semillas": "Organizaciones que articulan el intercambio y conservacion de semillas a escala territorial.",
    "Redes de consumo local": "Grupos de consumidores organizados para comprar directamente a productores locales.",
    "Redes de economía solidaria": "Articulacion de emprendimientos que priorizan cooperacion sobre competencia.",
    "Estudiar sobre regeneración": "Lectura, cursos y autoformacion sobre enfoques regenerativos.",
    "Practicar agroecología": "Implementacion directa de tecnicas agroecologicas en el espacio propio.",
    "Practicar meditación": "Practica contemplativa que cultiva atencion, calma y conexion interior.",
    "Practicar tai chi": "Arte marcial suave que integra movimiento, respiracion y meditacion.",
    "Practicar yoga": "Practica de posturas, respiracion y meditacion para bienestar integral.",
    "Participar en talleres de regeneración": "Asistencia activa a formaciones sobre diseno y practica regenerativa.",
    # ── Petalo 4: Salud y Bienestar ──
    "Alimentación basada en plantas": "Dieta centrada en vegetales, frutas, legumbres y cereales, reduciendo o eliminando productos animales.",
    "Consumo de alimentos locales": "Preferencia por alimentos producidos en la region, reduciendo huella de transporte.",
    "Dietas agroecológicas": "Alimentacion basada en productos cultivados sin agroquimicos.",
    "Cocina saludable comunitaria": "Preparacion colectiva de alimentos nutritivos, compartiendo saberes culinarios.",
    "Jardinería terapéutica": "Uso de la jardineria como herramienta de sanacion fisica y emocional.",
    "Baños de bosque urbanos": "Practica de inmersion sensorial en areas verdes para reducir estres (shinrin-yoku).",
    "Meditación en huertos": "Practica meditativa en contacto con la tierra y las plantas.",
    "Espacios de contemplación": "Rincones disenados para la quietud, la observacion y el descanso mental.",
    "Cultivo de plantas medicinales": "Produccion de hierbas con propiedades terapeuticas (menta, manzanilla, matico, boldo).",
    "Preparación de tinturas": "Extraccion de principios activos de plantas medicinales en alcohol.",
    "Preparación de pomadas": "Elaboracion de unguentos con plantas medicinales para uso topico.",
    "Preparación de infusiones": "Uso de hierbas secas o frescas para preparar tes e infusiones medicinales.",
    "Grupos de apoyo comunitario": "Espacios de encuentro donde vecinos se acompanan mutuamente en procesos de vida.",
    "Espacios de cuidado colectivo": "Organizacion comunitaria del cuidado de ninos, personas mayores o enfermas.",
    "Redes de cuidado mutuo": "Sistemas vecinales de ayuda reciproca ante emergencias o necesidades cotidianas.",
    "Yoga comunitario": "Clases de yoga gratuitas o a voluntad en espacios publicos o comunitarios.",
    "Tai chi en parques": "Practica grupal de tai chi en parques y plazas.",
    "Caminatas ecológicas": "Recorridos a pie por la naturaleza con foco en observacion y conexion ecologica.",
    "Bicicleteadas comunitarias": "Paseos colectivos en bicicleta que promueven movilidad sustentable y comunidad.",
    # ── Petalo 5: Finanzas y Economia ──
    "Mercados agroecológicos": "Ferias donde productores locales venden alimentos cultivados sin agroquimicos.",
    "Ferias de intercambio": "Eventos donde se intercambian productos y servicios sin usar dinero.",
    "Canastas comunitarias": "Compras colectivas organizadas que conectan directamente a productores y consumidores.",
    "Agricultura apoyada por la comunidad (CSA)": "Modelo donde consumidores financian por adelantado a un agricultor y reciben cosechas regulares.",
    "Cooperativas de producción": "Organizaciones de productores que trabajan colectivamente y comparten beneficios.",
    "Cooperativas de consumo": "Grupos de consumidores organizados para comprar alimentos de calidad a precio justo.",
    "Cooperativas de vivienda": "Organizaciones que gestionan colectivamente la propiedad y uso de viviendas.",
    "Bancos de tiempo": "Sistemas donde las personas intercambian horas de trabajo en vez de dinero.",
    "Monedas locales": "Monedas complementarias que circulan solo en una comunidad, fortaleciendo la economia local.",
    "Plataformas de trueque": "Espacios fisicos o digitales para intercambiar bienes y servicios sin dinero.",
    "Redes de intercambio de servicios": "Comunidades donde personas ofrecen y reciben servicios mutuamente.",
    "Producción de alimentos locales": "Emprendimientos dedicados a producir alimentos en la localidad.",
    "Viveros urbanos": "Negocios de propagacion y venta de plantas adaptadas al entorno urbano.",
    "Diseño de huertos urbanos": "Servicio profesional de diseno de espacios productivos en la ciudad.",
    "Educación ambiental": "Emprendimientos dedicados a formar personas en temas ecologicos y regenerativos.",
    "Consultoría regenerativa": "Asesoria profesional en diseno y transicion hacia practicas regenerativas.",
    "Compras a productores locales": "Preferencia por comprar directamente a quien produce, eliminando intermediarios.",
    "Reducción de consumo": "Practica consciente de consumir menos, priorizando lo necesario.",
    "Reparación de objetos": "Reparar en vez de reemplazar, extendiendo la vida util de los objetos.",
    "Reutilización de materiales": "Dar nuevo uso a materiales que serian descartados.",
    "Compras colectivas de alimentos": "Grupos que compran juntos para acceder a mejores precios y productos.",
    "Comprar a granel": "Compra sin envases individuales, reduciendo residuos de empaque.",
    "Evitar plásticos de un solo uso": "Eliminacion de bolsas, vasos y envases plasticos descartables.",
    "Comprar productos locales": "Preferencia por productos fabricados o cultivados en la region.",
    "Comprar colectivamente": "Organizarse con vecinos para comprar en conjunto a mejor precio.",
    "Evitar envases innecesarios": "Preferir productos con minimo empaque o sin empaque.",
    "Reparar antes de comprar": "Evaluar si un objeto puede repararse antes de adquirir uno nuevo.",
    "Compartir herramientas": "Uso comunitario de herramientas que no se necesitan a diario.",
    # ── Petalo 6: Gobernanza ──
    "Asambleas barriales": "Reuniones abiertas de vecinos para discutir y decidir sobre temas del barrio.",
    "Consejos comunitarios": "Organos de representacion vecinal que coordinan acciones territoriales.",
    "Mesas ambientales locales": "Espacios de dialogo entre vecinos, autoridades y organizaciones sobre temas ambientales.",
    "Recuperación de sitios eriazos": "Transformacion de terrenos abandonados en espacios verdes productivos.",
    "Creación de huertos comunitarios": "Establecimiento de espacios de cultivo colectivo en terrenos publicos o comunitarios.",
    "Parques comestibles urbanos": "Parques publicos disenados para producir alimentos accesibles a toda la comunidad.",
    "Jardines comunitarios": "Espacios verdes gestionados colectivamente por vecinos.",
    "Participación en planificación urbana": "Involucramiento activo de ciudadanos en decisiones de desarrollo de la ciudad.",
    "Presupuestos participativos": "Mecanismo donde vecinos deciden en que se invierte parte del presupuesto municipal.",
    "Defensa de áreas verdes": "Organizacion ciudadana para proteger parques, plazas y bosques amenazados.",
    "Cooperativas de vivienda": "Gestion colectiva de la vivienda como bien comun, no como mercancia.",
    "Comunidades intencionales urbanas": "Grupos de personas que eligen vivir juntas compartiendo valores y recursos.",
    "Fideicomisos de tierra comunitaria": "Modelo legal que protege la tierra del mercado especulativo, asegurando uso comunitario.",
    "Redes de agroecología urbana": "Articulacion de huertos, productores y consumidores agroecologicos en la ciudad.",
    "Redes de transición urbana": "Movimientos ciudadanos que preparan barrios para la transicion energetica y alimentaria.",
    "Redes de resiliencia comunitaria": "Organizaciones que fortalecen la capacidad de las comunidades para enfrentar crisis.",
    "Conectar con vecinos": "Acto basico de conocer, saludar y generar vinculos con quienes viven cerca.",
    "Participar en organizaciones locales": "Involucrarse activamente en juntas de vecinos, clubes deportivos u organizaciones del barrio.",
    "Participar en huertos comunitarios": "Sumarse como miembro activo a un huerto colectivo del barrio.",
    "Organizar actividades de barrio": "Tomar iniciativa para crear eventos que unan a los vecinos (fiestas, limpiezas, ferias).",
}


def get_description(action_name):
    """Return description for an action. Falls back to a generic message."""
    return GLOSARIO.get(action_name, f"Practica regenerativa relacionada con {action_name.lower()}.")
